"""Shared presentation resources (design tokens) for the desktop GUI."""

from app.gui.resources.tokens import (
    CARD_RADIUS,
    CONTROL_RADIUS,
    CONTROL_SPACING,
    FONT_FAMILY,
    LAYOUT_MARGIN,
    MONO_FONT,
    PANEL_SPACING,
    STEP_CURRENT_PROPERTY,
    STEP_CURRENT_VALUE,
    STEP_DONE_VALUE,
    STEP_FAILED_VALUE,
    STEP_PENDING_VALUE,
    WINDOW_DEFAULT_HEIGHT,
    WINDOW_DEFAULT_WIDTH,
    WINDOW_MIN_HEIGHT,
    WINDOW_MIN_WIDTH,
)

__all__ = [
    "CARD_RADIUS",
    "CONTROL_RADIUS",
    "CONTROL_SPACING",
    "FONT_FAMILY",
    "LAYOUT_MARGIN",
    "MONO_FONT",
    "PANEL_SPACING",
    "STEP_CURRENT_PROPERTY",
    "STEP_CURRENT_VALUE",
    "STEP_DONE_VALUE",
    "STEP_FAILED_VALUE",
    "STEP_PENDING_VALUE",
    "WINDOW_DEFAULT_HEIGHT",
    "WINDOW_DEFAULT_WIDTH",
    "WINDOW_MIN_HEIGHT",
    "WINDOW_MIN_WIDTH",
]
